### ISSUE TITLE
estream.to and thevideo.me

### ISSUE THREAD

**Issue by shdyy** [greatis/Anti-WebMiner#10]
These hosts are not miners but they use miners. So remove them and add the miners instead.

estream.to
thevideo.ch
thevideo.me
thevideo.us

estream.to uses these miner hosts:

m1.streaming.estream.to
m2.streaming.estream.to

thevideo uses these miner hosts:

www.assetscdn.stream
p1.assetscdn.stream
p2.assetscdn.stream
p3.assetscdn.stream

Previously thevideo was using these hosts, I guess they changed the address:

www.interestingz.pw
p1.interestingz.pw
p2.interestingz.pw
p3.interestingz.pw

**Comment by shdyy** [comment]
vidtodo.com/vidtudu.com uses these miner hosts

s1.vidtod.me
s2.vidtod.me
s3.vidtod.me

streamplay.to uses these hosts but blocking doesn't stop cpu usage

ws02cn.streamplay.to
ws03cn.streamplay.to

ws01cn.streamplay.to (possibly)

**Comment by greatis** [comment]
Thanks! Blacklist has been updated.
