### ISSUE TITLE
Can we get the ready-to-use hosts file from an http mirror?

### ISSUE THREAD

**Issue by claustromaniac** [greatis/Anti-WebMiner#3]
I use a more general hosts file manager app to merge and sanitize blacklists from different sources, and it seems it doesn't get along with https. An http mirror would be greatly appreciated, as it would help in keeping my list up to date without having to manually edit those entries every time. 

Thank you!

**Comment by greatis** [comment]
Hi,

Sorry! I don't know how to do it with Github. 
You can use a Curl or Wget to download.
I cannot maintain another http mirror.

**Comment by ColasNahaboo** [comment]
You can use curl or wget without issue. I have just made a script to maintain /etc/hosts on linux hosts that uses the host list directly at: https://raw.githubusercontent.com/greatis/Anti-WebMiner/master/hosts

My script "coin-miners-block" is free of use at http://hg.colas.nahaboo.net/coin-miners-block/

Thanks to greatis for your work!

**Comment by yermulnik** [comment]
For those who came across this issue (despite the project seems to be abandoned for several years already) looking for an automation for linux boxes (the `/etc/crontab` oneliner):
```
41 */3 * * * root sleep $(shuf -n 1 -i 0-900) && (flock -n 9 || exit 1; sed -r '/^# Anti-WebMiner Start /,/# Anti-WebMiner End/d' -i /etc/hosts && curl -fsS https://raw.githubusercontent.com/greatis/Anti-WebMiner/master/hosts >> /etc/hosts) 9>/var/lock/etc_hosts-crontab-anti_webminer
```
