### ISSUE TITLE
Senseless line in `hosts` file

### ISSUE THREAD

**Issue by yermulnik** [greatis/Anti-WebMiner#8]
There a senseless line in [Ready-to-use hosts file](https://raw.githubusercontent.com/greatis/Anti-WebMiner/master/hosts):
```0.0.0.0 185.14.28.10```

**Comment by greatis** [comment]
Thanks!
Fixed.

**Comment by yermulnik** [comment]
Apologies for not reporting earlier (haven't noticed before) — there are two more lines like that:
```
0.0.0.0 3104709642
0.0.0.0 52.80.10.9
```

ps: `3104709642` is a 32-bit decimal representation of `185.14.28.10`

**Comment by greatis** [comment]
Thanks for help!
You are right.

**Comment by yermulnik** [comment]
And these lines should be removed as they are senseless =)

**Comment by greatis** [comment]
Sure. Updated!
